# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='grade',
            name='full',
            field=models.IntegerField(default=0),
        ),
    ]
