# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0004_auto_20170414_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='grade',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
