# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0005_grade_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='credit',
            field=models.FloatField(default=0),
        ),
    ]
