# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 19:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0006_grade_credit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='grade',
            new_name='grade0',
        ),
    ]
