# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-16 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0007_auto_20170416_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='grade0',
            new_name='grade',
        ),
    ]
