# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0008_auto_20170416_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='mean',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='sd',
            field=models.FloatField(default=0),
        ),
    ]
