# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0009_auto_20170427_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='final_full',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='grade',
            name='final_score',
            field=models.FloatField(default=0),
        ),
    ]
